# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f516846224aeec1f69879b2abcf4919f3a33ca0c4dfdc83cb884d9161bdf9be720e5fedc171f5302eda27fd7eaeb8bfcd549b065fe42805927855fc0c6c4b77

test:
  secret_key_base: 08dcf371d98d40ad0dc31053b0beef895ae34dd41503efe10bfe70fa414fba23d5d0c81afc3b4cd69cb693d204426c47e7f6a43b317a50ba367443652f17fbac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
